### ISSUE TITLE
Load Balancing & Solar Charging

### ISSUE THREAD

**Issue by acejoh** [jagheterfredrik/wallbox-mqtt-bridge#72]
Hi,

First off, thanks for creating this application!
Would it be possible to add support for the configuration of the Dynamic Load Balancing & Solar Charging features of Wallbox chargers?

Kind regards,

Johannes

**Comment by mbfoo** [comment]
For solar charging without any cloud access, I am using [evcc.io](https://evcc.io/) in combination with this fork of this project: [wallbox-mqtt-bridge](https://github.com/sweber/wallbox-mqtt-bridge/)

These are the relevant parts of my evcc.yaml:
```
meters:
- name: wallboxpulsarmeter
  type: custom
  power:
    source: mqtt
    topic: wallbox/charging_power/state
    timeout: 180s
  energy:
    source: calc
    mul:
      - source: mqtt
        topic: wallbox/added_energy/state
        timeout: 180s
      - source: const
        value: 0.001
  currents:
    - source: mqtt
      topic: wallbox/charging_current_l1/state
    - source: mqtt
      topic: wallbox/charging_current_l2/state
    - source: mqtt
      topic: wallbox/charging_current_l3/state
      timeout: 180s

chargers:
- name: wallboxpulsarcharger
  type: custom
  status:
    source: mqtt
    topic: wallbox/control_pilot/state
  enabled: # charger enabled state (true/false or 0/1)
    source: mqtt
    topic: wallbox/charging_enable/state
  enable: # set charger enabled state (true/false or 0/1)
    source: mqtt
    topic: wallbox/charging_enable/set
    payload: ${enable:%d}
  maxcurrent: # set charger max current (A)
    source: mqtt
    topic: wallbox/max_charging_current/set

loadpoints:
- title: Wallbox
  charger: wallboxpulsarcharger
  meter: wallboxpulsarmeter
  vehicle: car
  mode: now
  enable:
    delay: 1m
    threshold: -3000
  disable:
    delay: 15m
    threshold: 2000
  priority: 2

```
